const name = "Raquel"
let last name = "jones"
let language = "JavaScript"
let createdYear = 1999
let price = 19.99j
let isOnSale = false
let salePercentage = 15
let stock = 0
let inStock = false
let selectedSize = "M"
let title = "Name of the Wind"
let author = "Patrick Rothfuss"
let pageCount = 722
let boodmark = 456
let hasRead = true
